jobs:
  complete_coveralls:
    needs: test-multi-python
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@57daa114ba54fd8e1c8563e8027325c0bf2f5e80
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
  lint-multi-os:
    name: Lint ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - uses: actions/cache@v1
      with:
        key: v0-${{ runner.os }}-pip-lint-${{ hashFiles('setup.py') }}
        path: ~/.cache/pip
        restore-keys: |
          v0-${{ runner.os }}-pip-lint-
          v0-${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[lint]
    - name: Run black
      run: black --check --verbose .
    - name: Run flake8
      run: flake8 --statistics
    - name: Run flynt
      run: flynt -vdf -tc -ll 1000 .
    - name: Run isort
      run: isort -cv .
    - name: Run pydocstyle
      run: pydocstyle prawcore
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
  test-multi-os:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - uses: actions/cache@v1
      with:
        key: v0-${{ runner.os }}-pip-test-${{ hashFiles('setup.py') }}
        path: ~/.cache/pip
        restore-keys: |
          v0-${{ runner.os }}-pip-test-
          v0-${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      run: pytest
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
  test-multi-python:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v1
      with:
        key: v0-${{ runner.os }}-pip-test-${{ hashFiles('setup.py') }}
        path: ~/.cache/pip
        restore-keys: |
          v0-${{ runner.os }}-pip-test-
          v0-${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
        pip install https://github.com/bboe/coveralls-python/archive/github_actions.zip
    - name: Test with pytest
      run: coverage run --source prawcore --module pytest
    - env:
        COVERALLS_PARALLEL: true
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Submit to coveralls
      run: coveralls
    - name: Check coverage
      run: coverage report -m --fail-under=100
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
name: CI
on: [pull_request, push]
